### ISSUE TITLE
Support for `pathlib.Path` objects?

### ISSUE THREAD

**Issue by vandalt** [spacetelescope/stpipe#139]
Hi!

I was wondering if `pathlib.Path` objects were supported in `stpipe` (and packages depending on it like `jwst`) or if support was planned in the future.

I wanted to report an example issue I encountered recently: using a `Path` object as input to `Step.run()` leads to the `_input_filename` attribute not being set because the `Path` falls in the `else` category [here](https://github.com/spacetelescope/stpipe/blob/2a976365406b11ae6f116fe0e97f529fee700b9c/src/stpipe/step.py?plain=1#L893-L902).

The simple fix for users is to use strings as input path, but it took me a bit of time to figure this out because I missed the error message in the log.

**Comment by jdavies-st** [comment]
Hi @vandalt, yes `pathlib.Path` objects should be supported.  Thanks for reporting the bug.
