### ISSUE TITLE
Parsing step's list arguments is broken

### ISSUE THREAD

**Issue by mcara** [spacetelescope/stpipe#71]
@jemorrison reported that parsing list arguments of steps does not work. Indeed, I verified that running `strun` with
```
--steps.resample.output_shape=500,800
```
which used to work before, no longer works:
```
ValueError: Config parameter 'output_shape': the value "500,800" is of the wrong type.
```

CC: @stscieisenhamer 

After some detective work, I determined that https://github.com/spacetelescope/stpipe/pull/57 broke support for list arguments.

**Comment by jdavies-st** [comment]
Note #69 is the same issue and has a solution available.
